(()=>{"use strict";
const $=id=>document.getElementById(id), sids=Object.keys(SIM_MAP.sensors), eids=Object.keys(SIM_MAP.exits), rids=["R1","R2","R3","R4","R5","R6"];
const st={models:{},ready:false,test:false,testN:0,testTimer:null,refreshTimer:null,values:{"0":{},"10":{},"20":{},"30":{}},routes:{},payload:null};
const sm={},em={};
function color(v){return v<25?"#2ba86c":v<50?"#e2b735":v<80?"#e98539":"#d53d3d"}
function status(x,age){$("badge").textContent=x;$("badge").className="badge "+(x==="LIVE"?"live":x==="DELAY"?"delay":"no");$("last").textContent=age==null?"수신 기록 없음":`데이터 나이 ${age.toFixed(1)}초`}
function msg(t){$("msg").textContent=t}
function build(){
 $("start").innerHTML=sids.map(x=>`<option ${x==="S20"?"selected":""}>${x}</option>`).join("");
 rids.forEach(x=>{let d=document.createElement("div");d.className="realcard";d.id="r-"+x;d.innerHTML=`<span>${x}</span><strong>0.0</strong><small>위험도</small>`;$("realCards").appendChild(d)});
 sids.forEach(x=>{let p=SIM_MAP.sensors[x],b=document.createElement("button");b.className="sensor";b.textContent=x.slice(1);b.style.left=p.x+"%";b.style.top=p.y+"%";$("sensorLayer").appendChild(b);sm[x]=b;let c=document.createElement("div");c.className="virtualcard";c.id="v-"+x;c.innerHTML=`<strong>${x}</strong><span>0.0</span>`;$("virtualCards").appendChild(c)});
 eids.forEach(x=>{let p=SIM_MAP.exits[x],d=document.createElement("div");d.className="exitmark";d.textContent=x;d.style.left=p.x+"%";d.style.top=p.y+"%";$("exitLayer").appendChild(d);em[x]=d});
 $("routes").innerHTML=["0","10","20","30"].map(h=>`<article><span>${h==="0"?"현재":h+"초 뒤"}</span><strong id="re${h}">-</strong><p id="rp${h}">-</p></article>`).join("")
}
async function loadModels(){try{for(const h of ["10","20","30"])st.models[h]=await tf.loadLayersModel(DASHBOARD_CONFIG.modelPaths[h]);st.ready=true;$("model").textContent="준비 완료";$("modelDetail").textContent="10·20·30초 모델 연결됨"}catch(e){st.ready=false;$("model").textContent="모델 없음";$("modelDetail").textContent="models 폴더 확인";msg("5단계 모델을 models 폴더에 복사하세요. 현재값과 A*는 시험 가능합니다.");console.error(e)}}
function interp(real){let out={};sids.forEach(id=>{let p=SIM_MAP.sensors[id],sum=0,ws=0;rids.forEach(r=>{let a=SIM_MAP.sensors[DASHBOARD_CONFIG.realSensorAnchors[r]],d=Math.hypot(p.x-a.x,p.y-a.y),w=1/Math.pow(d+3,2);sum+=(+real[r]||0)*w;ws+=w});out[id]=Math.max(0,Math.min(100,Math.round(sum/ws*10)/10))});return out}
async function predict(cur){let input=tf.tensor2d([sids.map(x=>cur[x]/100)],[1,30]);try{for(const h of ["10","20","30"]){if(!st.ready){st.values[h]={...cur};continue}let o=st.models[h].predict(input),a=await o.data();st.values[h]={};sids.forEach((x,i)=>st.values[h][x]=Math.max(0,Math.min(100,Math.round(a[i]*1000)/10)));o.dispose()}}finally{input.dispose()}}
function calc(){["0","10","20","30"].forEach(h=>st.routes[h]=PathFinder.findSafestExit($("start").value,st.values[h]))}
function draw(r){$("pathLayer").innerHTML="";Object.values(em).forEach(x=>x.classList.remove("recommended"));if(!r?.path?.length)return;let pts=r.path.map(x=>{let p=SIM_MAP.sensors[x]||SIM_MAP.exits[x];return `${p.x},${p.y}`}).join(" ");let l=document.createElementNS("http://www.w3.org/2000/svg","polyline");l.setAttribute("points",pts);l.setAttribute("class","routeLine");$("pathLayer").appendChild(l);em[r.exit]?.classList.add("recommended")}
function render(real={}){rids.forEach(x=>{let v=+real[x]||0,c=$("r-"+x);c.style.borderTopColor=color(v);c.querySelector("strong").textContent=v.toFixed(1)});let h=$("horizon").value,v=st.values[h]||{},r=st.routes[h];sids.forEach(x=>{let n=+v[x]||0;sm[x].style.background=color(n);sm[x].classList.toggle("current",x===$("start").value);let c=$("v-"+x);c.style.borderTopColor=color(n);c.querySelector("span").textContent=n.toFixed(1)});let lab=h==="0"?"현재":h+"초 뒤";$("shown").textContent=lab;$("mapHorizon").textContent=lab;$("exit").textContent=r?.exit||"없음";$("route").textContent=r?.path?.join(" → ")||"경로 없음";draw(r);["0","10","20","30"].forEach(x=>{$("re"+x).textContent=st.routes[x]?.exit||"없음";$("rp"+x).textContent=st.routes[x]?.path?.join(" → ")||"경로 없음"})}
async function process(p,test){st.payload=p;let real={};rids.forEach(x=>real[x]=+p.sensors?.[x]||0);st.values["0"]=interp(real);await predict(st.values["0"]);calc();render(real);$("device").textContent=p.device_id||"-";$("rssi").textContent="RSSI: "+(p.wifi_rssi??"-");$("serverTime").textContent=p.server_time?new Date(p.server_time).toLocaleString("ko-KR"):"-";$("age").textContent=(+p.age_seconds||0).toFixed(1)+"초";$("seq").textContent=p.sequence??"-";$("mode").textContent=test?"시험 데이터":"실제 데이터";status(p.status||"LIVE",+p.age_seconds||0)}
async function fetchNow(){if(st.test)return;let u=$("api").value.trim().replace(/\/+$/,"");if(!u){msg("Apps Script 주소를 입력하세요.");return}try{let sep=u.includes("?")?"&":"?",r=await fetch(u+sep+"action=latest",{cache:"no-store"}),p=await r.json();if(!p.ok)throw Error(p.error||"응답 오류");await process(p,false);msg("최신 센서값을 받았습니다.")}catch(e){status("NO DATA",null);msg("수신 실패: "+e.message)}}
function testPayload(){st.testN++;let t=st.testN;return{ok:true,status:"LIVE",age_seconds:.2,server_time:new Date().toISOString(),device_id:"TEST-ESP32",sequence:t,wifi_rssi:-48,sensors:{R1:Math.min(100,10+t*1.2),R2:Math.min(100,14+t*1.8),R3:Math.min(100,20+t*2.6),R4:Math.min(100,12+t*.8),R5:Math.min(100,8+t*.4),R6:Math.min(100,6+t*.25)}}}
function startTest(){stopTest();st.test=true;st.testN=0;let run=()=>process(testPayload(),true);run();st.testTimer=setInterval(run,2000);msg("시험 데이터 실행 중")}
function stopTest(){clearInterval(st.testTimer);st.testTimer=null;st.test=false;$("mode").textContent="실제 데이터"}
function save(){localStorage.setItem("fd_api",$("api").value.trim());localStorage.setItem("fd_start",$("start").value);localStorage.setItem("fd_refresh",$("refresh").value);refreshTimer();msg("설정을 저장했습니다.")}
function refreshTimer(){clearInterval(st.refreshTimer);let n=+$("refresh").value;if(n)st.refreshTimer=setInterval(fetchNow,n)}
function download(){let heads=["sensor_id","current","t10","t20","t30"],rows=sids.map(x=>[x,st.values["0"][x]??"",st.values["10"][x]??"",st.values["20"][x]??"",st.values["30"][x]??""]);let csv="\uFEFF"+heads.join(",")+"\n"+rows.map(x=>x.join(",")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),a=document.createElement("a");a.href=u;a.download="fire_dashboard_snapshot.csv";a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function events(){$("save").onclick=save;$("fetch").onclick=fetchNow;$("test").onclick=startTest;$("stop").onclick=()=>{stopTest();msg("시험 모드를 중지했습니다.")};$("horizon").onchange=()=>render(st.payload?.sensors||{});$("start").onchange=()=>{calc();render(st.payload?.sensors||{})};$("refresh").onchange=refreshTimer;$("download").onclick=download}
async function init(){build();$("api").value=localStorage.getItem("fd_api")||DASHBOARD_CONFIG.apiUrl;$("start").value=localStorage.getItem("fd_start")||"S20";$("refresh").value=localStorage.getItem("fd_refresh")||"5000";events();refreshTimer();await loadModels();if($("api").value)fetchNow()}init();
})();